modLoader = "javafml"
loaderVersion = "[38,)"
license = "MIT License"
[[mods]]
modId="constructionwand"
version="${file.jarVersion}"
displayName="Construction Wand"
displayURL="https://github.com/Theta-Dev/ConstructionWand"
logoFile="logo.png"
authors="ThetaDev"
description='''
Construction Wands make building easier!

With a Construction Wand you can place multiple blocks (up to 1024) at once, extending you build on the side you're facing.
Sneak+Right click to activate angel mode which allows you to place a block at the opposite side of the block facing you.
If you concentrate enough, you can even conjure a block in mid air!

This is my first minecraft mod. May the odds be ever in your favor.
'''
[[dependencies.constructionwand]]
    modId="forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
    side="BOTH"
[[dependencies.constructionwand]]
    modId="minecraft"
mandatory = true
versionRange = "[1.18, 1.19)"
ordering = "NONE"
    side="BOTH"
